server:
  port: 18000
spring:
  application:
    name: report-server
  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database-plateform: org.hibernate.dialect.MySQL5InnoDBDialect  
  datasource:                          
    url: jdbc:mysql://127.0.0.1:3306/report?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root  
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
# 日志配置:
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
    cn.segema.cloud.mall: ERROR
  file: /data/logs/report/report-server.log 

